name: Packages CD

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  pull-requests: write
  pages: write

jobs:
  release-please:
    timeout-minutes: 5
    runs-on: ubuntu-24.04
    outputs:
      # You need to explicitly output the tag name and release_created for each package
      # This assumes your release-please-config.json and .release-please-manifest.json
      # are set up to handle multiple packages and will output these.
      "packages/core--tag_name": ${{ steps.release.outputs['packages/core--tag_name'] }}
      "packages/core--release_created": ${{ steps.release.outputs['packages/core--release_created'] }}
      "packages/middleware-retry-after--tag_name": ${{ steps.release.outputs['packages/middleware-retry-after--tag_name'] }}
      "packages/middleware-retry-after--release_created": ${{ steps.release.outputs['packages/middleware-retry-after--release_created'] }}
      "packages/middleware-retry-status--tag_name": ${{ steps.release.outputs['packages/middleware-retry-status--tag_name'] }}
      "packages/middleware-retry-status--release_created": ${{ steps.release.outputs['packages/middleware-retry-status--release_created'] }}
      "packages/middleware-base-url--tag_name": ${{ steps.release.outputs['packages/middleware-base-url--tag_name'] }}
      "packages/middleware-base-url--release_created": ${{ steps.release.outputs['packages/middleware-base-url--release_created'] }}
      "packages/middleware-authorization--tag_name": ${{ steps.release.outputs['packages/middleware-authorization--tag_name'] }}
      "packages/middleware-authorization--release_created": ${{ steps.release.outputs['packages/middleware-authorization--release_created'] }}
      "packages/middleware-query-params--tag_name": ${{ steps.release.outputs['packages/middleware-query-params--tag_name'] }}
      "packages/middleware-query-params--release_created": ${{ steps.release.outputs['packages/middleware-query-params--release_created'] }}
      "packages/middleware-headers--tag_name": ${{ steps.release.outputs['packages/middleware-headers--tag_name'] }}
      "packages/middleware-headers--release_created": ${{ steps.release.outputs['packages/middleware-headers--release_created'] }}
      "packages/middleware-response-error--tag_name": ${{ steps.release.outputs['packages/middleware-response-error--tag_name'] }}
      "packages/middleware-response-error--release_created": ${{ steps.release.outputs['packages/middleware-response-error--release_created'] }}
      "packages/qfetch--tag_name": ${{ steps.release.outputs['packages/qfetch--tag_name'] }}
      "packages/qfetch--release_created": ${{ steps.release.outputs['packages/qfetch--release_created'] }}
      "packages/middlewares--tag_name": ${{ steps.release.outputs['packages/middlewares--tag_name'] }}
      "packages/middlewares--release_created": ${{ steps.release.outputs['packages/middlewares--release_created'] }}
      # Add more outputs for other packages here

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Print release outputs for debugging
        continue-on-error: true
        run: |
          echo "Release outputs:"
          echo "${{ toJson(steps.release.outputs) }}"

  core:
    needs: release-please
    if: ${{ needs.release-please.outputs['packages/core--release_created'] == 'true' }}
    uses: ./.github/workflows/_template.package-cd.yaml
    with:
      package_path: "packages/core"
      package_name: "@qfetch/core"
      package_tag: ${{ needs.release-please.outputs['packages/core--tag_name'] }}

  middleware-retry-after:
    needs: release-please
    if: ${{ needs.release-please.outputs['packages/middleware-retry-after--release_created'] == 'true' }}
    uses: ./.github/workflows/_template.package-cd.yaml
    with:
      package_path: "packages/middleware-retry-after"
      package_name: "@qfetch/middleware-retry-after"
      package_tag: ${{ needs.release-please.outputs['packages/middleware-retry-after--tag_name'] }}

  middleware-retry-status:
    needs: release-please
    if: ${{ needs.release-please.outputs['packages/middleware-retry-status--release_created'] == 'true' }}
    uses: ./.github/workflows/_template.package-cd.yaml
    with:
      package_path: "packages/middleware-retry-status"
      package_name: "@qfetch/middleware-retry-status"
      package_tag: ${{ needs.release-please.outputs['packages/middleware-retry-status--tag_name'] }}

  middleware-base-url:
    needs: release-please
    if: ${{ needs.release-please.outputs['packages/middleware-base-url--release_created'] == 'true' }}
    uses: ./.github/workflows/_template.package-cd.yaml
    with:
      package_path: "packages/middleware-base-url"
      package_name: "@qfetch/middleware-base-url"
      package_tag: ${{ needs.release-please.outputs['packages/middleware-base-url--tag_name'] }}

  middleware-authorization:
    needs: release-please
    if: ${{ needs.release-please.outputs['packages/middleware-authorization--release_created'] == 'true' }}
    uses: ./.github/workflows/_template.package-cd.yaml
    with:
      package_path: "packages/middleware-authorization"
      package_name: "@qfetch/middleware-authorization"
      package_tag: ${{ needs.release-please.outputs['packages/middleware-authorization--tag_name'] }}

  middleware-query-params:
    needs: release-please
    if: ${{ needs.release-please.outputs['packages/middleware-query-params--release_created'] == 'true' }}
    uses: ./.github/workflows/_template.package-cd.yaml
    with:
      package_path: "packages/middleware-query-params"
      package_name: "@qfetch/middleware-query-params"
      package_tag: ${{ needs.release-please.outputs['packages/middleware-query-params--tag_name'] }}

  middleware-headers:
    needs: release-please
    if: ${{ needs.release-please.outputs['packages/middleware-headers--release_created'] == 'true' }}
    uses: ./.github/workflows/_template.package-cd.yaml
    with:
      package_path: "packages/middleware-headers"
      package_name: "@qfetch/middleware-headers"
      package_tag: ${{ needs.release-please.outputs['packages/middleware-headers--tag_name'] }}

  middleware-response-error:
    needs: release-please
    if: ${{ needs.release-please.outputs['packages/middleware-response-error--release_created'] == 'true' }}
    uses: ./.github/workflows/_template.package-cd.yaml
    with:
      package_path: "packages/middleware-response-error"
      package_name: "@qfetch/middleware-response-error"
      package_tag: ${{ needs.release-please.outputs['packages/middleware-response-error--tag_name'] }}

  qfetch:
    needs: release-please
    if: ${{ needs.release-please.outputs['packages/qfetch--release_created'] == 'true' }}
    uses: ./.github/workflows/_template.package-cd.yaml
    with:
      package_path: "packages/qfetch"
      package_name: "@qfetch/qfetch"
      package_tag: ${{ needs.release-please.outputs['packages/qfetch--tag_name'] }}

  middlewares:
    needs: release-please
    if: ${{ needs.release-please.outputs['packages/middlewares--release_created'] == 'true' }}
    uses: ./.github/workflows/_template.package-cd.yaml
    with:
      package_path: "packages/middlewares"
      package_name: "@qfetch/middlewares"
      package_tag: ${{ needs.release-please.outputs['packages/middlewares--tag_name'] }}

  documentation:
    needs: release-please
    if: >-
      ${{
        needs.release-please.outputs['packages/core--release_created'] == 'true' ||
        needs.release-please.outputs['packages/middleware-retry-after--release_created'] == 'true' ||
        needs.release-please.outputs['packages/middleware-retry-status--release_created'] == 'true' ||
        needs.release-please.outputs['packages/middleware-base-url--release_created'] == 'true' ||
        needs.release-please.outputs['packages/middleware-authorization--release_created'] == 'true' ||
        needs.release-please.outputs['packages/middleware-query-params--release_created'] == 'true' ||
        needs.release-please.outputs['packages/middleware-headers--release_created'] == 'true' ||
        needs.release-please.outputs['packages/middleware-response-error--release_created'] == 'true' ||
        needs.release-please.outputs['packages/qfetch--release_created'] == 'true' ||
        needs.release-please.outputs['packages/middlewares--release_created'] == 'true'
      }}
    uses: ./.github/workflows/docs.yaml
